language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install: |
  DOCKER="i386/ubuntu:16.04"

  docker pull $DOCKER
  docker run --name bc -v $TRAVIS_BUILD_DIR:/ETe --cap-add SYS_ADMIN --device /dev/fuse -td $DOCKER /bin/bash

install: |
  docker exec bc apt update
  docker exec bc apt -y install git cmake p7zip-full wget libfuse2 build-essential libsdl2-dev libgl1-mesa-dev libjpeg-dev

script: |
  cd $TRAVIS_BUILD_DIR/src
  mkdir $TRAVIS_BUILD_DIR/src/build
  cd $TRAVIS_BUILD_DIR/src/build
  mkdir $TRAVIS_BUILD_DIR/src/build/travis
  cd $TRAVIS_BUILD_DIR/src/build/travis

  CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DUSE_SDL2=TRUE -DSystemProcessor=i386"

  docker exec bc sh -c "cd /ETe/src/build/travis && cmake $CMAKE_OPTIONS ../../../
  docker exec bc sh -c "cd /ETe/src/build/travis && cmake --build . --config Release"

after_script: |
  docker stop bc;


# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux-cmake.sh; fi
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux.sh; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-macos.sh; fi

#deploy:
#  provider: releases
#  file_glob: true
#  skip_cleanup: true
#  draft: true
#  prerelease: false
#  api_key:
#    secure: "n5NzbUHEvac0eXKCMoFxb/AUftv/Y2RD6cOwLvq8opBhw809ekbiCS2rUh3WYHzYsa0DKgWUrOtJWT9mWv1ySaoEPuo0Dl+YHriH/nupBzVbNUCF64Bz51hLl9LOANlP/uuCeRih3r6a2QvKG1oSf/OtLp2rhkWLS6zhyj3tnbnyPdONaxCwyY4QOWJY1nBJa7YPQ20yIWs0L1bKFXpJC+IDqz6R65a1s3tgLmnQrmIOlPgfRZtiXBrO47LZlGhe3NEZOgXtr1ar8kK4SwK6w23ykSJIen9Jh48jj96ZUSdQvEuMVTUYzfyPvnDaIzkA7ChhKn6BKb8/dHQ+JD7s81Wz2wBU0RuE63nLszQVS8LFK5NgRtyWr9YpuY+IHlPjZPP1n4OukJ9FNkANf0Z+wZVhk847xVcjkjMu3ZahpKxn+2L5lyIOOF1L1NGt/WqGLPVmZ4rw8EwP44+zb9SXowe3KmTQcMi6ShD/6RKiubpxeuHvwNlIhP8X/se90sqttBb4fUohf57U5/Fu1nzBwYGolDON4V19JH0Uvqq5nr0Es8J96ckHXI5dwIMrrNkjlGgvCnQ+03eKcY3wtFMC/aVfLh+mZl5EUA3YwzYJu39GYZ6KmOi4Cjq9j23wmp+QLdTr+0jXUrVgQumJyb/zV8P87WbTvYvvQviyc+cHHA0="
#  file: "ete*.7z"
#  on:
#    tags: true

notifications:
  email: false
