os: Visual Studio 2017
configuration: Release
version: ETe-{branch}-{build}

#enviroment:
  

build_script:
  - ps: |
      cd src
      $env:CONFIGURATION=$(configuration)
      msbuild wolf.sln /m /p:PlatformToolset=v141_xp;Configuration=$env:CONFIGURATION /t:botlib;libjpeg;renderer;Splines;wolf;wolfded

      if (! $?) {
        throw "Build failed."
      }
