version: ETe-{branch}-{build}
image: Visual Studio 2017
configuration: Release

#environment variable version
environment:
  BUILD_CONFIGURATION: Release

# custom build script to specify projects and xp mode
build_script:
  - ps: |
      cd src
      msbuild /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION" .\botlib\botlib.vcxproj
      msbuild /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION" .\jpec-8c\libjpeg.vcxproj
      msbuild /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION" .\splines\Splines.vcxproj
      msbuild /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION" .\renderer\renderer.vcxproj
      msbuild /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION" wolf.vcxproj
      msbuild /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION" wolfded.vcxproj

      if (! $?) {
        throw "Build failed."
      }
