version: ETe-{branch}-{build}
image: Visual Studio 2017
configuration: Release

#environment variable version
environment:
  BUILD_CONFIGURATION: Release

# custom build script to specify xp mode and listed configuration
# wolf.sln currently only has the projects included that are built due to difficulty of making it only build ones we want on appveyor
build_script:
  - ps: |
      cd src
      msbuild wolf.sln /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION"

      if (! $?) {
        throw "Build failed."
      }
