os: Visual Studio 2017
configuration: Debug
version: ETe-{branch}-{build}

build_script:
  - ps: |
      cd src
      msbuild /m /p:PlatformToolset=v141_xp;Configuration=$env:CONFIGURATION /t:botlib;libjpeg;renderer;Splines;wolf;wolfded wolf.sln

      if (! $?) {
        throw "Build failed."
      }
