version: ETe-{branch}-{build}
image: Visual Studio 2017
configuration: Release

#environment variable version
environment:
  BUILD_CONFIGURATION: Release

# custom build script to specify projects and xp mode
build_script:
  - ps: |
      cd src
      msbuild wolf.sln /m /p:PlatformToolset="v141_xp" /p:Configuration="$env:BUILD_CONFIGURATION" /t:botlib;libjpeg;renderer;Splines;wolf;wolfded

      if (! $?) {
        throw "Build failed."
      }
