set(SPLINES_SRCS
    "splines/math_angles.cpp"
    "splines/math_matrix.cpp"
    "splines/math_quaternion.cpp"
    "splines/math_vector.cpp"
    "splines/q_parse.cpp"
    #"splines/q_shared.c"
    "splines/splines.cpp"
    "splines/util_str.cpp"
)